// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASFN5ICc-5dnpiaMjlDA7tbdCnmKTPRUk',
    appId: '1:1032616268679:web:16c80548406fbf803db922',
    messagingSenderId: '1032616268679',
    projectId: 'flusnip',
    authDomain: 'flusnip.firebaseapp.com',
    storageBucket: 'flusnip.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAKetGZ4I-bfdEsS_GwLgT2Xigucn3T9E',
    appId: '1:1032616268679:android:6d901c1a5f72b7563db922',
    messagingSenderId: '1032616268679',
    projectId: 'flusnip',
    storageBucket: 'flusnip.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtwlvIpAn7x6EGlBPNe3ybEIXU7ni6rWk',
    appId: '1:1032616268679:ios:58b73cb729d153a43db922',
    messagingSenderId: '1032616268679',
    projectId: 'flusnip',
    storageBucket: 'flusnip.appspot.com',
    iosClientId: '1032616268679-bu6cftvsjkb6cluff96p4l9q9iqovnqi.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttersnips',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtwlvIpAn7x6EGlBPNe3ybEIXU7ni6rWk',
    appId: '1:1032616268679:ios:60d3348ee5d4dde23db922',
    messagingSenderId: '1032616268679',
    projectId: 'flusnip',
    storageBucket: 'flusnip.appspot.com',
    iosClientId: '1032616268679-ie3269pqcqi2pj2dauc9l5d411ipo75f.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttersnips.RunnerTests',
  );
}
