// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLh6oCjHHrlZWl0NaYdJNGAVYyp4y_oYc',
    appId: '1:1070671776693:web:bf0d7e31982da2e5dde7fc',
    messagingSenderId: '1070671776693',
    projectId: 'fluttersnips-1fbad',
    authDomain: 'fluttersnips-1fbad.firebaseapp.com',
    storageBucket: 'fluttersnips-1fbad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuh8WJfe1GV3pN4gRRM62FjMyYFqyJOuU',
    appId: '1:1070671776693:android:55151aa432a25ce8dde7fc',
    messagingSenderId: '1070671776693',
    projectId: 'fluttersnips-1fbad',
    storageBucket: 'fluttersnips-1fbad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc-FeDbKltE-byvGObY7SAc8FLgafz_9g',
    appId: '1:1070671776693:ios:190653f0c5fb0c1adde7fc',
    messagingSenderId: '1070671776693',
    projectId: 'fluttersnips-1fbad',
    storageBucket: 'fluttersnips-1fbad.appspot.com',
    iosBundleId: 'com.example.fluttersnips',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc-FeDbKltE-byvGObY7SAc8FLgafz_9g',
    appId: '1:1070671776693:ios:992fff8ec0db73d3dde7fc',
    messagingSenderId: '1070671776693',
    projectId: 'fluttersnips-1fbad',
    storageBucket: 'fluttersnips-1fbad.appspot.com',
    iosBundleId: 'com.example.fluttersnips.RunnerTests',
  );
}
